### ISSUE TITLE
Bug in error handling 

### ISSUE THREAD

**Issue by mitra42** [levansuper/readable-stream-clone#2]
This useful little utility has a problem - if it receives an error then it tries to push an error , which of course fails (you can't push an object on readable-streams).
Instead it should emit the error which has the expected effect.
Note that this error has to be handled on each of the clones as they'll all get the error, but that turns out to be the behavior wanted anyway as each clone may handle it differently.

Note - I posted the fix as a PR #1 but it doesn't appear @levansuper  is monitoring this utility so posting it here as an issue so others can see !  

There is a fork that fixes this bug that you might want to use until/unless the PR gets merged. 
https://github.com/mitra42/readable-stream-clone

**Comment by levansuper** [comment]
Thanks for the PR. It's merged.
