### ISSUE TITLE
License missing in package.json / License file missing

### ISSUE THREAD

**Issue by eek** [levansuper/readable-stream-clone#4]
Repository is missing a License file / package.json is missing a license as well. 

Can you add one to your project?

Would love to use this but having no license is a stop for us.

Thanks!

**Comment by parimalyeole1** [comment]
@mitra42, @levansuper 

Is it possible for you to add license, only thing stoping us from using it.

**Comment by mitra42** [comment]
@parimalyeole1  sorry, I just fixed one bug, its @levansuper 's package.

**Comment by parimalyeole1** [comment]
Thanks @mitra42 

@levansuper use this https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository
and publish to npm if possible.

**Comment by levansuper** [comment]
@eek  Thanks for suggestion and sorry for the delay. the MIT license is added
